name: commet
description: Find your space

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  google_fonts: ^3.0.1
  matrix: ^0.15.12
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
  just_the_tooltip: ^0.0.12
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.2
  desktop_drop: ^0.4.1
  test: ^1.22.0
  tiamat:
    path: tiamat/tiamat/
  scaled_app: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_launcher_icons:
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon/icon_square_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon/icon_circle_512.png"
  windows:
    generate: true
    image_path: "assets/images/app_icon/icon_circle_512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon/icon_square_512.png"

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: T # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb-dir: lib/l10n

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/placeholder/avatars/
    - assets/images/placeholder/generic/

  shaders:
    - assets/shader/texture_coordinate.frag